### ISSUE TITLE
Issue with `withFallback` and `Date`

### ISSUE THREAD

**Issue by andrey-gatash** [scopt/scopt#156]
Hi,

I'm using v. 3.7.0. I have an issue using `withFallback` with `java.util.Date` typed opt. Here's the minimal code: 

```Scala
import java.text.SimpleDateFormat
import java.util.Date

import scopt.Read
import scopt.Read.reads

implicit val dateRead: Read[Date] = reads(new SimpleDateFormat("yyyy/MM/dd").parse)

case class SimpleParams(from: Date = new Date())

new scopt.OptionParser[SimpleParams]("scopt") {
  opt[Date]("from")
    .action((v, c) => c.copy(from = v))
    .withFallback(() => new Date())
}.parse(Seq(), SimpleParams())
```
I get e.g.
```
Error: Option --from expects a Scala duration but was given 'Tue Sep 26 17:22:30 EDT 2017'
```

It works fine if `withFallback` line is commented out. Any advice? Thanks.

**Comment by EnverOsmanov** [comment]
I have debugged the issue.
1) **scopt** library converts the date provided by `withFallback` to String and tries to handle it as if it was received from parameters - which means parsing it using your `dateRead`.  The problem is that you use custom date formatter so `new Date()` converted to `String` can't be parsed by `dateRead`:
```Scala
implicit val dateRead: Read[Date] = Read.reads(new SimpleDateFormat("yyyy/MM/dd").parse)
dateRead.reads(new Date().toString)
// java.text.ParseException: Unparseable date: "Fri Jan 04 18:38:25 EET 2019"
```
2) **scopt** library shows `Scala duration` error message for any `ParseException`!

@eed3si9n This problem is still actual for **4.0.0-RC2**. The least we can do is to show a more relevant error message.
