### ISSUE TITLE
Command-based arguments: children {...} only adopts the last child

### ISSUE THREAD

**Issue by tiagoboldt** [scopt/scopt#20]
I want to have the following scenario

```
App [client|server] <args>
```

Running as client:

```
App server
```

Running as server:

```
App client arg1 arg2 arg3
```

Implemented with: 

``` scala
     cmd("client")
       .action { (_, c) =>
       c.copy(mode = "c") }
       .text("Run as Client.")
       .children{

      arg[String]("a").required()
        .action { (x, c) => c.copy(a = x) }
        .text("..")

      arg[String]("b").required()
        .action { (x, c) => c.copy(b = x) }
        .text("..")

      arg[String]("c").required()
        .action { (x, c) => c.copy(c = x) }
        .text("..")
    }

    cmd("server")
      .action { (_, c) => c.copy(mode = "s") }
      .text("Run in Server mode")
```

If I try to just "App server", I get a message stating that I'm not inputing the required arguments. Being children of "client", I believe that only inside this command these arguments should be required. If this by design or a bug?

Regards

**Comment by softprops** [comment]
I actually just ran into this issue the other day [here](https://github.com/softprops/pullboy/blob/master/src/main/scala/config.scala) if any of actiona's children are required and you are provide actionb, it seems the requirement for options for actiona are still validated regardless. I think this is a bug.

**Comment by eed3si9n** [comment]
It's a bug. Required check currently is probably unaware of the command.

**Comment by eed3si9n** [comment]
Contrary to our guesses, the validation logic was only using `pendingArgs`, the arguments that are available for parsing.

 The problem was in my documentation of `children` method. Since `children` accepts a vararg of options, what's required is using `()` instead of `{}`, and passing comma separated list of arguments. Since `{}` is interpreted as a block, only the last argument was interpreted to be the child.

This explains the fact that only `a` and `b` are tripping the validation, but not `c`:

```
scopt-test> run server
[info] Running Test server
Error: Missing argument a
Error: Missing argument b
scopt 3.x
Usage: scopt [client|server] <args>...

Command: client c
Run as Client.
  c
        ..
  a
        ..
  b
        ..
Command: server
Run in Server mode
```

Here's your code rewritten using `()`:

``` scala
  val parser = new scopt.OptionParser[Config]("scopt") {
    head("scopt", "3.x")

    cmd("client") action { (_, c) =>
      c.copy(mode = "c") } text("Run as Client.") children(
      arg[String]("a") action { (x, c) => c.copy(a = x) } text(".."),
      arg[String]("b") action { (x, c) => c.copy(b = x) } text(".."),
      arg[String]("c") action { (x, c) => c.copy(c = x) } text("..")
    )

    cmd("server") action { (_, c) =>
      c.copy(mode = "s") } text("Run in Server mode")
  }
```

`arg` is required by default, so no need to call `required()`.
