### ISSUE TITLE
Simple short options

### ISSUE THREAD

**Issue by avdv** [scopt/scopt#214]
Hey, I am using scopt in my project and I like it!

Only one thing bothers me a bit: it always demands a long option "name". I am used to GNU getopt and Ruby's optparse for example and neither of these have this *limitation*.

IMO, an option should either have a long or short option, or both.

Thanks!

**Comment by eed3si9n** [comment]
The limitation is by design. The initial version of [scala-options](https://github.com/aaronharnly/scala-options/blob/ef2c8c41181b40cc34856ddcae5185ec08aa4474/src/main/scala/net/harnly/aaron/options/OptionsParser.scala#L9-L16) even required both short and long options.

Short options are great for typing, but difficult to read and comprehend what's going on. So I think shell scripts should always use long option names, which is more readable and Google-able. From that point of view, a program that exposes an option without corresponding long option is broken.

**Comment by avdv** [comment]
Fair enough, I guess I am just too lazy thinking about long option names.

Actually, I am writing a drop-in replacement for another program and simply wanted to mimic the command line options as far as possible. But it's not a big deal if the the options are a superset of the original ones.

Cheers.
