### ISSUE TITLE
Repeated parameters

### ISSUE THREAD

**Issue by joprice** [scopt/scopt#277]
Is there a way to allow a parameter to be provided multiple times?

**Comment by Esardes** [comment]
can you pass it in a list? (like the -j parameter in the example)

**Comment by joprice** [comment]
Unfortunately, I have to maintain an existing interface that sends parameters in this way.

**Comment by pradis** [comment]
I think that you can use unbounded method to do this.
E.g. 
 ```
opt[Map[String, String]]('k', "kwargs")
          .valueName("k1=v1,k2=v2...")
          .unbounded()
          .action((x, c) => c.copy(kwargs = c.kwargs ++ x))
          .text("key value arguments"),
```
in this case you can use -k k1=v1,k2=v2 or -k k1=v1 -k k2=v2

**Comment by avdv** [comment]
I am a bit surprised that `.unbounded()` isn't the default for options since it is pretty common that you can repeat flags / options multiple times for a command which is usually just equivalent to specifying it once.

For example if you have some shell alias with some default options and you want to specify some options when using the alias you would have to be careful *not* to repeat an option which is already defined in your alias, or make all options unbounded.

IMO, only-once-options are a rare case -- I cannot think of a use case right now where I would want this out-of-the-box...
