### ISSUE TITLE
Usage text: common options merge with last command specific options

### ISSUE THREAD

**Issue by ziggystar** [scopt/scopt#35]
I get the following usage message:

```
Usage: experiment-coffee [infer|learn] [options] <args>...

Command: infer data...
do parameter estimation; the model may have NaN values as parameters
  data...
        one or more activity distribution sequence files
Command: learn ground-truth...
infer marginals; the model must be completely specified
  ground-truth...
        one or more ground-truth sequence files
  mln
        the mln model file to be used
  --help
```

The problem is that only `ground-truth` is a child of `infer`, and not `mln` or `--help`. But you can't tell this from the usage text. Maybe you can insert a `Common Options:` without indentation after the last command specific option.

**Comment by eed3si9n** [comment]
scopt generally tries to output in the order you defined the options, and I did notice it does meld the common options if you define them after the commands when at the time of development. You could define common options first like the example in README or insert `note("...\n")` in between. I figured scopt doing less in this case is better since you have the control on how things would look like.
