### ISSUE TITLE
Q: How to deal with mandatory options?

### ISSUE THREAD

**Issue by rintcius** [scopt/scopt#9]
How can i represent a mandatory option correctly? For example this use case:

If I have 

```
someCommand --mandatory needed
```

then I would like to have an option class like this:

```
case class MyOption(mandatory: String)
```

I cannot find how to specify the parser and initial option object correctly. I can solve it by creating an option class like this:

```
case class MyTmpOption(mandatory: Option[String] = None)
```

and then "parse" that further into MyOption, returning an error when the field is still none, but this feels a bit awkward. 

Any suggestions how to do this in a better way?

**Comment by eed3si9n** [comment]
There's no support for mandatory options at the moment.
Even if we accept the concept of mandatory options, wouldn't they be dependent on existence of `someCommand` in most cases?
Using `Option[String]` seems like a reasonable workaround here. Have you tried [subcommands in Scallop](https://github.com/Rogach/scallop/wiki/Subcommands)?

**Comment by rintcius** [comment]
Hi Eugene, thanks for your response.

I am not sure what you mean exactly with mandatory options dependent on existence of `someCommand`, but I know that I don't mean subcommands :)

I had a look at Scallop some time ago, but it looked a bit rough back then. It seems to support required options though https://github.com/Rogach/scallop/wiki/Basic-usage

```
val apples = opt[Int]("apples", required = true)
```

**Comment by eed3si9n** [comment]
Here's an example:

```
git checkout --foo value
git pull --bar value
```

If one's using argument as a command (`someCommand`, `checkout`, `pull`), I argue that in many cases the mandatory options are conditionally mandatory. In the above case, `--foo value` is required only when it's `git checkout`. That may not be your case, but if I were to implement it, that's how I would think, which is what subcommand feature provides.

But at least for `git`, mandatory inputs are handled as positional argument, rather than option. We write

```
git checkout origin master
```

Positional argument is another feature missing in scopt, but available in [other fine libraries](http://stackoverflow.com/questions/2315912/scala-best-way-to-parse-command-line-parameters-cli).

**Comment by rintcius** [comment]
Yeah, probably mandatory options make most sense in the context of subcommands.

In my case I have to deal with existing commands though, where I have no control over. So i'll probably live with the option workaround or switch to Scallop.

(BTW that link is a good source indeed; coincidently it's where I added Scallop)

**Comment by eed3si9n** [comment]
> coincidently it's where I added Scallop

right. that's why I asked if you've tried subcommand from Scallop. I just updated my "accepted" answer trying to promote Scallop a bit more. For now, I'm closing this case.

**Comment by rintcius** [comment]
Ok, great. Thanks for your time.
