### ISSUE TITLE
project does neither include a LICENSE file nor include a copyright notice

### ISSUE THREAD

**Issue by wookietreiber** [scopt/scopt#91]
When I am **redistributing scopt**, e.g. in binary form, i.e. a pre-compiled jar, as part of an application created with e.g. sbt-native-packager, I am supposed to **include the LICENSE** file in that distribution, **according to the MIT license terms**.

scopt does only say in its README that its license is the MIT license but **there is no LICENSE file, including the copyright notice, for me to copy and put in a distribution**.

**Please add a LICENSE file to the project** (MIT license text can be copied from [here](http://opensource.org/licenses/MIT), copyright notice must be edited accordingly), so it is possible to redistribute scopt according to its licensing terms.

**Comment by Johann-ChristophJacob** [comment]
I very much second that!
Supplying a LICENSE file would also resolve the [ambiguity](https://en.wikipedia.org/wiki/MIT_License#Various_versions) of just stating "MIT License.".

**Comment by colindean** [comment]
I would very much like this.

**Comment by informarte** [comment]
I compared scopt to scallop and, while both tools satisfy my requirements, I concluded that scopt's approach to specifying the command line is simpler and results in more readable code. However, due to the licensing issues, I will go for scallop for the time being, but I will happily switch to scopt as soon as the the scopt authors provide a proper LICENSE file.

**Comment by informarte** [comment]
Wow, that was quick, thanks!
